#!/bin/sh
# Copyright (c) 2014 Oblong Industries
# License: MIT
#
set -e

SRCDIR=`dirname "$0"`
SRCDIR=`cd "$SRCDIR"; /bin/pwd`

if test -d "$SRCDIR"/recipes
then
    RECIPES="$SRCDIR"/recipes
else
    RECIPES=/usr/share/yobuild/recipes
fi

usage() {
    cat << _EOF_
List recipies known by yb_buildone
Usage: $0 
_EOF_
}

case $1 in
"")
    ls $RECIPES;;
-h|--help)
    usage; exit 0;;
*)
    usage; exit 1;;
esac
